gateway:
  host: "127.0.0.1"  # 仅本地调试使用， 镜像部署暴露 0.0.0.0:8081
  port: 8081
logger:
  level: "info"
  encoding: "json"
  filename: "log/gateway.log"
  max-size: 100
  max-backups: 3
  max-age: 7
  compress: true
  console: true